apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: zenimax-node-pool
spec:
  template:
    metadata:
      labels:
        name: zenimax-node-pool
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: zenimax-node-class

      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["t2.medium", "t3.medium"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
        - key: "eks.amazonaws.com/instance-cpu"
          operator: In
          values: ["2" ,"4", "8"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-east-1a", "us-east-1b", "us-east-1c"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]

  limits:
    cpu: "20"
    memory: 20Gi