apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-service.fullname" . }}-config
  labels:
    {{- include "python-service.labels" . | nindent 4 }}
data:
  DEBUG: {{ .Values.config.debug | quote }}
  HOST: {{ .Values.config.host | quote }}
  PORT: {{ .Values.config.port | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_USERNAME: {{ .Values.config.dbUsername | quote }}