apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "node-service.fullname" . }}-config
  labels:
    {{- include "node-service.labels" . | nindent 4 }}
data:
  JAVA_SERVICE_URL: {{ .Values.config.javaServiceUrl | quote }}
  PYTHON_SERVICE_URL: {{ .Values.config.pythonServiceUrl | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_USERNAME: {{ .Values.config.dbUsername | quote }}
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: {{ .Values.config.port | quote }}