apiVersion: v1
kind: Secret
metadata:
  name: {{ include "node-service.fullname" . }}-secret
  labels:
    {{- include "node-service.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ .Values.secret.dbHost | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc | quote }}