apiVersion: v1
kind: Secret
metadata:
  name: node-service-secret
type: Opaque
data:
  DB_HOST: ZGV2LXplbmltYXgtdG9kby1hcHAtcmRzLmN6ZzVkNDRuMnR5bC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=  
  DB_PASSWORD: YWRtaW4xMjM=  # admin123 (base64 encoded)
