# Default values for java-service
replicaCount: 2

image:
  repository: java-service
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 8080

resources:
  limits:
    cpu: "500m"
    memory: "1Gi"
  requests:
    cpu: "250m"
    memory: "512Mi"

readinessProbe:
  path: /api/health
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  path: /api/health
  initialDelaySeconds: 60
  periodSeconds: 15

config:
  dbName: "todoappdb"
  dbUsername: "admin"

secret:
  dbHost: "mysql-db.cmc8ienqykxp.us-east-1.rds.amazonaws.com"
  dbPassword: "admin123"