apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "java-service.fullname" . }}-config
  labels:
    {{- include "java-service.labels" . | nindent 4 }}
data:
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_USERNAME: {{ .Values.config.dbUsername | quote }}